# Containers management
init:
	echo "\n\033[33mBuild des conteneurs\033[39m"
	dc build
	echo "\n\033[33mLancement des conteneurs\033[39m"
	dc up -d

# Symfony project creation
create-sf-project:
	echo "\n\033[33mCréation du projet Symfony...\033[39m"
	rm -rf web/*
	symfony new web --version="7.4.*" --webapp