FROM php:8.2-fpm-alpine

# Composer environment variables
ENV COMPOSER_HOME=/composer \
    PATH=/composer/vendor/bin:$PATH \
    COMPOSER_ALLOW_SUPERUSER=1

# System dependencies and common PHP extensions
RUN apk add --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        icu-dev \
        libxml2-dev \
        libxslt-dev \
        sqlite-dev \
        freetype-dev \
        libpng-dev \
        libjpeg-turbo-dev \
        libzip-dev \
        linux-headers \
        libsodium-dev \
        oniguruma-dev \
    && apk add --no-cache \
        bash \
        git \
        mariadb-client \
        libwebp-dev \
        ca-certificates \
        icu-libs \
        libxslt \
        libzip \
    && docker-php-ext-configure gd --with-freetype --with-webp --with-jpeg \
    && docker-php-ext-install \
        intl \
        mbstring \
        pdo \
        pdo_sqlite \
        simplexml \
        sodium \
        xml \
        xmlwriter \
        zip \
        xsl \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && apk del .build-deps

# Install Composer 2
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Install Symfony CLI
RUN apk add --no-cache openssl \
    && update-ca-certificates \
    && wget https://get.symfony.com/cli/installer -O - | bash \
    && mv /root/.symfony*/bin/symfony /usr/local/bin/symfony

# Configuration fixuid
ADD fixuid.tar.gz /usr/local/bin
RUN chown root:root /usr/local/bin/fixuid && chmod 4755 /usr/local/bin/fixuid && mkdir -p /etc/fixuid
COPY fixuid.yml /etc/fixuid/config.yml

# Custom PHP configuration
COPY sf7-start-php.ini /usr/local/etc/php/php.ini

WORKDIR /var/www/html